/// Shared currency constants
library;

class CurrencyOption {
  final String id;
  final String code;
  final String name;
  final String symbol;
  final int decimals;
  final String format;
  final String label;

  const CurrencyOption({
    this.id = '',
    required this.code,
    required this.name,
    required this.symbol,
    required this.decimals,
    required this.format,
    required this.label,
  });
}

const List<CurrencyOption> defaultCurrencyOptions = [
  CurrencyOption(
    code: 'INR',
    name: 'Indian Rupee',
    symbol: 'rs',
    decimals: 2,
    format: '##,##,##0.00',
    label: 'INR - Indian Rupee',
  ),
  CurrencyOption(
    code: 'USD',
    name: 'US Dollar',
    symbol: r'$',
    decimals: 2,
    format: '1,234,567.89',
    label: 'USD - US Dollar',
  ),
  CurrencyOption(
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    decimals: 2,
    format: '1,234,567.89',
    label: 'EUR - Euro',
  ),
  CurrencyOption(
    code: 'GBP',
    name: 'Pound Sterling',
    symbol: '£',
    decimals: 2,
    format: '1,234,567.89',
    label: 'GBP - Pound Sterling',
  ),
  CurrencyOption(
    code: 'AFN',
    name: 'Afghani',
    symbol: 'AFN',
    decimals: 2,
    format: '1,234,567.89',
    label: 'AFN - Afghani',
  ),
  CurrencyOption(
    code: 'ALL',
    name: 'Lek',
    symbol: 'ALL',
    decimals: 2,
    format: '1,234,567.89',
    label: 'ALL - Lek',
  ),
  CurrencyOption(
    code: 'DZD',
    name: 'Algerian Dinar',
    symbol: 'DZD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'DZD - Algerian Dinar',
  ),
  CurrencyOption(
    code: 'AOA',
    name: 'Kwanza',
    symbol: 'AOA',
    decimals: 2,
    format: '1,234,567.89',
    label: 'AOA - Kwanza',
  ),
  CurrencyOption(
    code: 'XCD',
    name: 'East Caribbean Dollar',
    symbol: 'XCD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'XCD - East Caribbean Dollar',
  ),
  CurrencyOption(
    code: 'ARS',
    name: 'Argentine Peso',
    symbol: 'ARS',
    decimals: 2,
    format: '1,234,567.89',
    label: 'ARS - Argentine Peso',
  ),
  CurrencyOption(
    code: 'AMD',
    name: 'Armenian Dram',
    symbol: 'AMD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'AMD - Armenian Dram',
  ),
  CurrencyOption(
    code: 'AWG',
    name: 'Aruban Florin',
    symbol: 'AWG',
    decimals: 2,
    format: '1,234,567.89',
    label: 'AWG - Aruban Florin',
  ),
  CurrencyOption(
    code: 'AUD',
    name: 'Australian Dollar',
    symbol: 'AUD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'AUD - Australian Dollar',
  ),
  CurrencyOption(
    code: 'AZN',
    name: 'Azerbaijan Manat',
    symbol: 'AZN',
    decimals: 2,
    format: '1,234,567.89',
    label: 'AZN - Azerbaijan Manat',
  ),
  CurrencyOption(
    code: 'BSD',
    name: 'Bahamian Dollar',
    symbol: 'BSD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BSD - Bahamian Dollar',
  ),
  CurrencyOption(
    code: 'BHD',
    name: 'Bahraini Dinar',
    symbol: 'BHD',
    decimals: 3,
    format: '1,234,567.890',
    label: 'BHD - Bahraini Dinar',
  ),
  CurrencyOption(
    code: 'BDT',
    name: 'Taka',
    symbol: 'BDT',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BDT - Taka',
  ),
  CurrencyOption(
    code: 'BBD',
    name: 'Barbados Dollar',
    symbol: 'BBD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BBD - Barbados Dollar',
  ),
  CurrencyOption(
    code: 'BYN',
    name: 'Belarusian Ruble',
    symbol: 'BYN',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BYN - Belarusian Ruble',
  ),
  CurrencyOption(
    code: 'BZD',
    name: 'Belize Dollar',
    symbol: 'BZD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BZD - Belize Dollar',
  ),
  CurrencyOption(
    code: 'XOF',
    name: 'CFA Franc BCEAO',
    symbol: 'XOF',
    decimals: 0,
    format: '1,234,567',
    label: 'XOF - CFA Franc BCEAO',
  ),
  CurrencyOption(
    code: 'BMD',
    name: 'Bermudian Dollar',
    symbol: 'BMD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BMD - Bermudian Dollar',
  ),
  CurrencyOption(
    code: 'BTN',
    name: 'Ngultrum',
    symbol: 'BTN',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BTN - Ngultrum',
  ),
  CurrencyOption(
    code: 'BOB',
    name: 'Boliviano',
    symbol: 'BOB',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BOB - Boliviano',
  ),
  CurrencyOption(
    code: 'BAM',
    name: 'Convertible Mark',
    symbol: 'BAM',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BAM - Convertible Mark',
  ),
  CurrencyOption(
    code: 'BWP',
    name: 'Pula',
    symbol: 'BWP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BWP - Pula',
  ),
  CurrencyOption(
    code: 'NOK',
    name: 'Norwegian Krone',
    symbol: 'NOK',
    decimals: 2,
    format: '1,234,567.89',
    label: 'NOK - Norwegian Krone',
  ),
  CurrencyOption(
    code: 'BRL',
    name: 'Brazilian Real',
    symbol: 'R\$',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BRL - Brazilian Real',
  ),
  CurrencyOption(
    code: 'BND',
    name: 'Brunei Dollar',
    symbol: 'BND',
    decimals: 2,
    format: '1,234,567.89',
    label: 'BND - Brunei Dollar',
  ),
  CurrencyOption(
    code: 'BIF',
    name: 'Burundi Franc',
    symbol: 'BIF',
    decimals: 0,
    format: '1,234,567',
    label: 'BIF - Burundi Franc',
  ),
  CurrencyOption(
    code: 'CVE',
    name: 'Cabo Verde Escudo',
    symbol: 'CVE',
    decimals: 2,
    format: '1,234,567.89',
    label: 'CVE - Cabo Verde Escudo',
  ),
  CurrencyOption(
    code: 'KHR',
    name: 'Riel',
    symbol: 'KHR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'KHR - Riel',
  ),
  CurrencyOption(
    code: 'XAF',
    name: 'CFA Franc BEAC',
    symbol: 'XAF',
    decimals: 0,
    format: '1,234,567',
    label: 'XAF - CFA Franc BEAC',
  ),
  CurrencyOption(
    code: 'CAD',
    name: 'Canadian Dollar',
    symbol: 'CAD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'CAD - Canadian Dollar',
  ),
  CurrencyOption(
    code: 'KYD',
    name: 'Cayman Islands Dollar',
    symbol: 'KYD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'KYD - Cayman Islands Dollar',
  ),
  CurrencyOption(
    code: 'CLP',
    name: 'Chilean Peso',
    symbol: 'CLP',
    decimals: 0,
    format: '1,234,567',
    label: 'CLP - Chilean Peso',
  ),
  CurrencyOption(
    code: 'CNY',
    name: 'Yuan Renminbi',
    symbol: '¥',
    decimals: 2,
    format: '1,234,567.89',
    label: 'CNY - Yuan Renminbi',
  ),
  CurrencyOption(
    code: 'COP',
    name: 'Colombian Peso',
    symbol: 'COP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'COP - Colombian Peso',
  ),
  CurrencyOption(
    code: 'KMF',
    name: 'Comorian Franc',
    symbol: 'KMF',
    decimals: 0,
    format: '1,234,567',
    label: 'KMF - Comorian Franc',
  ),
  CurrencyOption(
    code: 'CDF',
    name: 'Congolese Franc',
    symbol: 'CDF',
    decimals: 2,
    format: '1,234,567.89',
    label: 'CDF - Congolese Franc',
  ),
  CurrencyOption(
    code: 'NZD',
    name: 'New Zealand Dollar',
    symbol: 'NZD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'NZD - New Zealand Dollar',
  ),
  CurrencyOption(
    code: 'CRC',
    name: 'Costa Rican Colon',
    symbol: '₡',
    decimals: 2,
    format: '1,234,567.89',
    label: 'CRC - Costa Rican Colon',
  ),
  CurrencyOption(
    code: 'CUP',
    name: 'Cuban Peso',
    symbol: 'CUP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'CUP - Cuban Peso',
  ),
  CurrencyOption(
    code: 'XCG',
    name: 'Caribbean Guilder',
    symbol: 'XCG',
    decimals: 2,
    format: '1,234,567.89',
    label: 'XCG - Caribbean Guilder',
  ),
  CurrencyOption(
    code: 'CZK',
    name: 'Czech Koruna',
    symbol: 'Kč',
    decimals: 2,
    format: '1,234,567.89',
    label: 'CZK - Czech Koruna',
  ),
  CurrencyOption(
    code: 'DKK',
    name: 'Danish Krone',
    symbol: 'DKK',
    decimals: 2,
    format: '1,234,567.89',
    label: 'DKK - Danish Krone',
  ),
  CurrencyOption(
    code: 'DJF',
    name: 'Djibouti Franc',
    symbol: 'DJF',
    decimals: 0,
    format: '1,234,567',
    label: 'DJF - Djibouti Franc',
  ),
  CurrencyOption(
    code: 'DOP',
    name: 'Dominican Peso',
    symbol: 'DOP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'DOP - Dominican Peso',
  ),
  CurrencyOption(
    code: 'EGP',
    name: 'Egyptian Pound',
    symbol: 'EGP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'EGP - Egyptian Pound',
  ),
  CurrencyOption(
    code: 'SVC',
    name: 'El Salvador Colon',
    symbol: 'SVC',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SVC - El Salvador Colon',
  ),
  CurrencyOption(
    code: 'ERN',
    name: 'Nakfa',
    symbol: 'ERN',
    decimals: 2,
    format: '1,234,567.89',
    label: 'ERN - Nakfa',
  ),
  CurrencyOption(
    code: 'SZL',
    name: 'Lilangeni',
    symbol: 'SZL',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SZL - Lilangeni',
  ),
  CurrencyOption(
    code: 'ETB',
    name: 'Ethiopian Birr',
    symbol: 'ETB',
    decimals: 2,
    format: '1,234,567.89',
    label: 'ETB - Ethiopian Birr',
  ),
  CurrencyOption(
    code: 'FKP',
    name: 'Falkland Islands Pound',
    symbol: 'FKP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'FKP - Falkland Islands Pound',
  ),
  CurrencyOption(
    code: 'FJD',
    name: 'Fiji Dollar',
    symbol: 'FJD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'FJD - Fiji Dollar',
  ),
  CurrencyOption(
    code: 'XPF',
    name: 'CFP Franc',
    symbol: 'XPF',
    decimals: 0,
    format: '1,234,567',
    label: 'XPF - CFP Franc',
  ),
  CurrencyOption(
    code: 'GMD',
    name: 'Dalasi',
    symbol: 'GMD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'GMD - Dalasi',
  ),
  CurrencyOption(
    code: 'GEL',
    name: 'Lari',
    symbol: 'GEL',
    decimals: 2,
    format: '1,234,567.89',
    label: 'GEL - Lari',
  ),
  CurrencyOption(
    code: 'GHS',
    name: 'Ghana Cedi',
    symbol: 'GHS',
    decimals: 2,
    format: '1,234,567.89',
    label: 'GHS - Ghana Cedi',
  ),
  CurrencyOption(
    code: 'GIP',
    name: 'Gibraltar Pound',
    symbol: 'GIP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'GIP - Gibraltar Pound',
  ),
  CurrencyOption(
    code: 'GTQ',
    name: 'Quetzal',
    symbol: 'GTQ',
    decimals: 2,
    format: '1,234,567.89',
    label: 'GTQ - Quetzal',
  ),
  CurrencyOption(
    code: 'GNF',
    name: 'Guinean Franc',
    symbol: 'GNF',
    decimals: 0,
    format: '1,234,567',
    label: 'GNF - Guinean Franc',
  ),
  CurrencyOption(
    code: 'GYD',
    name: 'Guyana Dollar',
    symbol: 'GYD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'GYD - Guyana Dollar',
  ),
  CurrencyOption(
    code: 'HTG',
    name: 'Gourde',
    symbol: 'HTG',
    decimals: 2,
    format: '1,234,567.89',
    label: 'HTG - Gourde',
  ),
  CurrencyOption(
    code: 'HNL',
    name: 'Lempira',
    symbol: 'HNL',
    decimals: 2,
    format: '1,234,567.89',
    label: 'HNL - Lempira',
  ),
  CurrencyOption(
    code: 'HKD',
    name: 'Hong Kong Dollar',
    symbol: 'HKD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'HKD - Hong Kong Dollar',
  ),
  CurrencyOption(
    code: 'HUF',
    name: 'Forint',
    symbol: 'HUF',
    decimals: 2,
    format: '1,234,567.89',
    label: 'HUF - Forint',
  ),
  CurrencyOption(
    code: 'ISK',
    name: 'Iceland Krona',
    symbol: 'ISK',
    decimals: 0,
    format: '1,234,567',
    label: 'ISK - Iceland Krona',
  ),
  CurrencyOption(
    code: 'IDR',
    name: 'Rupiah',
    symbol: 'Rp',
    decimals: 2,
    format: '1,234,567.89',
    label: 'IDR - Rupiah',
  ),
  CurrencyOption(
    code: 'IRR',
    name: 'Iranian Rial',
    symbol: 'IRR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'IRR - Iranian Rial',
  ),
  CurrencyOption(
    code: 'IQD',
    name: 'Iraqi Dinar',
    symbol: 'IQD',
    decimals: 3,
    format: '1,234,567.890',
    label: 'IQD - Iraqi Dinar',
  ),
  CurrencyOption(
    code: 'ILS',
    name: 'New Israeli Sheqel',
    symbol: '₪',
    decimals: 2,
    format: '1,234,567.89',
    label: 'ILS - New Israeli Sheqel',
  ),
  CurrencyOption(
    code: 'JMD',
    name: 'Jamaican Dollar',
    symbol: 'JMD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'JMD - Jamaican Dollar',
  ),
  CurrencyOption(
    code: 'JPY',
    name: 'Yen',
    symbol: '¥',
    decimals: 0,
    format: '1,234,567',
    label: 'JPY - Yen',
  ),
  CurrencyOption(
    code: 'JOD',
    name: 'Jordanian Dinar',
    symbol: 'JOD',
    decimals: 3,
    format: '1,234,567.890',
    label: 'JOD - Jordanian Dinar',
  ),
  CurrencyOption(
    code: 'KZT',
    name: 'Tenge',
    symbol: 'KZT',
    decimals: 2,
    format: '1,234,567.89',
    label: 'KZT - Tenge',
  ),
  CurrencyOption(
    code: 'KES',
    name: 'Kenyan Shilling',
    symbol: 'KES',
    decimals: 2,
    format: '1,234,567.89',
    label: 'KES - Kenyan Shilling',
  ),
  CurrencyOption(
    code: 'KPW',
    name: 'North Korean Won',
    symbol: 'KPW',
    decimals: 2,
    format: '1,234,567.89',
    label: 'KPW - North Korean Won',
  ),
  CurrencyOption(
    code: 'KRW',
    name: 'Won',
    symbol: '₩',
    decimals: 0,
    format: '1,234,567',
    label: 'KRW - Won',
  ),
  CurrencyOption(
    code: 'KWD',
    name: 'Kuwaiti Dinar',
    symbol: 'KWD',
    decimals: 3,
    format: '1,234,567.890',
    label: 'KWD - Kuwaiti Dinar',
  ),
  CurrencyOption(
    code: 'KGS',
    name: 'Som',
    symbol: 'KGS',
    decimals: 2,
    format: '1,234,567.89',
    label: 'KGS - Som',
  ),
  CurrencyOption(
    code: 'LAK',
    name: 'Lao Kip',
    symbol: 'LAK',
    decimals: 2,
    format: '1,234,567.89',
    label: 'LAK - Lao Kip',
  ),
  CurrencyOption(
    code: 'LBP',
    name: 'Lebanese Pound',
    symbol: 'LBP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'LBP - Lebanese Pound',
  ),
  CurrencyOption(
    code: 'LSL',
    name: 'Loti',
    symbol: 'LSL',
    decimals: 2,
    format: '1,234,567.89',
    label: 'LSL - Loti',
  ),
  CurrencyOption(
    code: 'ZAR',
    name: 'Rand',
    symbol: 'ZAR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'ZAR - Rand',
  ),
  CurrencyOption(
    code: 'LRD',
    name: 'Liberian Dollar',
    symbol: 'LRD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'LRD - Liberian Dollar',
  ),
  CurrencyOption(
    code: 'LYD',
    name: 'Libyan Dinar',
    symbol: 'LYD',
    decimals: 3,
    format: '1,234,567.890',
    label: 'LYD - Libyan Dinar',
  ),
  CurrencyOption(
    code: 'CHF',
    name: 'Swiss Franc',
    symbol: 'CHF',
    decimals: 2,
    format: '1,234,567.89',
    label: 'CHF - Swiss Franc',
  ),
  CurrencyOption(
    code: 'MOP',
    name: 'Pataca',
    symbol: 'MOP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MOP - Pataca',
  ),
  CurrencyOption(
    code: 'MGA',
    name: 'Malagasy Ariary',
    symbol: 'MGA',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MGA - Malagasy Ariary',
  ),
  CurrencyOption(
    code: 'MWK',
    name: 'Malawi Kwacha',
    symbol: 'MWK',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MWK - Malawi Kwacha',
  ),
  CurrencyOption(
    code: 'MYR',
    name: 'Malaysian Ringgit',
    symbol: 'MYR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MYR - Malaysian Ringgit',
  ),
  CurrencyOption(
    code: 'MVR',
    name: 'Rufiyaa',
    symbol: 'MVR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MVR - Rufiyaa',
  ),
  CurrencyOption(
    code: 'MRU',
    name: 'Ouguiya',
    symbol: 'MRU',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MRU - Ouguiya',
  ),
  CurrencyOption(
    code: 'MUR',
    name: 'Mauritius Rupee',
    symbol: 'MUR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MUR - Mauritius Rupee',
  ),
  CurrencyOption(
    code: 'MXN',
    name: 'Mexican Peso',
    symbol: 'MXN',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MXN - Mexican Peso',
  ),
  CurrencyOption(
    code: 'MDL',
    name: 'Moldovan Leu',
    symbol: 'MDL',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MDL - Moldovan Leu',
  ),
  CurrencyOption(
    code: 'MNT',
    name: 'Tugrik',
    symbol: 'MNT',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MNT - Tugrik',
  ),
  CurrencyOption(
    code: 'MAD',
    name: 'Moroccan Dirham',
    symbol: 'MAD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MAD - Moroccan Dirham',
  ),
  CurrencyOption(
    code: 'MZN',
    name: 'Mozambique Metical',
    symbol: 'MZN',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MZN - Mozambique Metical',
  ),
  CurrencyOption(
    code: 'MMK',
    name: 'Kyat',
    symbol: 'MMK',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MMK - Kyat',
  ),
  CurrencyOption(
    code: 'NAD',
    name: 'Namibia Dollar',
    symbol: 'NAD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'NAD - Namibia Dollar',
  ),
  CurrencyOption(
    code: 'NPR',
    name: 'Nepalese Rupee',
    symbol: 'NPR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'NPR - Nepalese Rupee',
  ),
  CurrencyOption(
    code: 'NIO',
    name: 'Cordoba Oro',
    symbol: 'NIO',
    decimals: 2,
    format: '1,234,567.89',
    label: 'NIO - Cordoba Oro',
  ),
  CurrencyOption(
    code: 'NGN',
    name: 'Naira',
    symbol: '₦',
    decimals: 2,
    format: '1,234,567.89',
    label: 'NGN - Naira',
  ),
  CurrencyOption(
    code: 'MKD',
    name: 'Denar',
    symbol: 'MKD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'MKD - Denar',
  ),
  CurrencyOption(
    code: 'OMR',
    name: 'Rial Omani',
    symbol: 'OMR',
    decimals: 3,
    format: '1,234,567.890',
    label: 'OMR - Rial Omani',
  ),
  CurrencyOption(
    code: 'PKR',
    name: 'Pakistan Rupee',
    symbol: 'PKR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'PKR - Pakistan Rupee',
  ),
  CurrencyOption(
    code: 'PAB',
    name: 'Balboa',
    symbol: 'PAB',
    decimals: 2,
    format: '1,234,567.89',
    label: 'PAB - Balboa',
  ),
  CurrencyOption(
    code: 'PGK',
    name: 'Kina',
    symbol: 'PGK',
    decimals: 2,
    format: '1,234,567.89',
    label: 'PGK - Kina',
  ),
  CurrencyOption(
    code: 'PYG',
    name: 'Guarani',
    symbol: '₲',
    decimals: 0,
    format: '1,234,567',
    label: 'PYG - Guarani',
  ),
  CurrencyOption(
    code: 'PEN',
    name: 'Sol',
    symbol: 'PEN',
    decimals: 2,
    format: '1,234,567.89',
    label: 'PEN - Sol',
  ),
  CurrencyOption(
    code: 'PHP',
    name: 'Philippine Peso',
    symbol: '₱',
    decimals: 2,
    format: '1,234,567.89',
    label: 'PHP - Philippine Peso',
  ),
  CurrencyOption(
    code: 'PLN',
    name: 'Zloty',
    symbol: 'PLN',
    decimals: 2,
    format: '1,234,567.89',
    label: 'PLN - Zloty',
  ),
  CurrencyOption(
    code: 'QAR',
    name: 'Qatari Rial',
    symbol: 'QAR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'QAR - Qatari Rial',
  ),
  CurrencyOption(
    code: 'RON',
    name: 'Romanian Leu',
    symbol: 'RON',
    decimals: 2,
    format: '1,234,567.89',
    label: 'RON - Romanian Leu',
  ),
  CurrencyOption(
    code: 'RUB',
    name: 'Russian Ruble',
    symbol: '₽',
    decimals: 2,
    format: '1,234,567.89',
    label: 'RUB - Russian Ruble',
  ),
  CurrencyOption(
    code: 'RWF',
    name: 'Rwanda Franc',
    symbol: 'RWF',
    decimals: 0,
    format: '1,234,567',
    label: 'RWF - Rwanda Franc',
  ),
  CurrencyOption(
    code: 'SHP',
    name: 'Saint Helena Pound',
    symbol: 'SHP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SHP - Saint Helena Pound',
  ),
  CurrencyOption(
    code: 'WST',
    name: 'Tala',
    symbol: 'WST',
    decimals: 2,
    format: '1,234,567.89',
    label: 'WST - Tala',
  ),
  CurrencyOption(
    code: 'STN',
    name: 'Dobra',
    symbol: 'STN',
    decimals: 2,
    format: '1,234,567.89',
    label: 'STN - Dobra',
  ),
  CurrencyOption(
    code: 'SAR',
    name: 'Saudi Riyal',
    symbol: 'SAR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SAR - Saudi Riyal',
  ),
  CurrencyOption(
    code: 'RSD',
    name: 'Serbian Dinar',
    symbol: 'RSD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'RSD - Serbian Dinar',
  ),
  CurrencyOption(
    code: 'SCR',
    name: 'Seychelles Rupee',
    symbol: 'SCR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SCR - Seychelles Rupee',
  ),
  CurrencyOption(
    code: 'SLE',
    name: 'Leone',
    symbol: 'SLE',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SLE - Leone',
  ),
  CurrencyOption(
    code: 'SGD',
    name: 'Singapore Dollar',
    symbol: 'SGD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SGD - Singapore Dollar',
  ),
  CurrencyOption(
    code: 'SBD',
    name: 'Solomon Islands Dollar',
    symbol: 'SBD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SBD - Solomon Islands Dollar',
  ),
  CurrencyOption(
    code: 'SOS',
    name: 'Somali Shilling',
    symbol: 'SOS',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SOS - Somali Shilling',
  ),
  CurrencyOption(
    code: 'SSP',
    name: 'South Sudanese Pound',
    symbol: 'SSP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SSP - South Sudanese Pound',
  ),
  CurrencyOption(
    code: 'LKR',
    name: 'Sri Lanka Rupee',
    symbol: 'LKR',
    decimals: 2,
    format: '1,234,567.89',
    label: 'LKR - Sri Lanka Rupee',
  ),
  CurrencyOption(
    code: 'SDG',
    name: 'Sudanese Pound',
    symbol: 'SDG',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SDG - Sudanese Pound',
  ),
  CurrencyOption(
    code: 'SRD',
    name: 'Surinam Dollar',
    symbol: 'SRD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SRD - Surinam Dollar',
  ),
  CurrencyOption(
    code: 'SEK',
    name: 'Swedish Krona',
    symbol: 'SEK',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SEK - Swedish Krona',
  ),
  CurrencyOption(
    code: 'SYP',
    name: 'Syrian Pound',
    symbol: 'SYP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'SYP - Syrian Pound',
  ),
  CurrencyOption(
    code: 'TWD',
    name: 'New Taiwan Dollar',
    symbol: 'TWD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'TWD - New Taiwan Dollar',
  ),
  CurrencyOption(
    code: 'TJS',
    name: 'Somoni',
    symbol: 'TJS',
    decimals: 2,
    format: '1,234,567.89',
    label: 'TJS - Somoni',
  ),
  CurrencyOption(
    code: 'TZS',
    name: 'Tanzanian Shilling',
    symbol: 'TZS',
    decimals: 2,
    format: '1,234,567.89',
    label: 'TZS - Tanzanian Shilling',
  ),
  CurrencyOption(
    code: 'THB',
    name: 'Baht',
    symbol: '฿',
    decimals: 2,
    format: '1,234,567.89',
    label: 'THB - Baht',
  ),
  CurrencyOption(
    code: 'TOP',
    name: 'Pa’anga',
    symbol: 'TOP',
    decimals: 2,
    format: '1,234,567.89',
    label: 'TOP - Pa’anga',
  ),
  CurrencyOption(
    code: 'TTD',
    name: 'Trinidad and Tobago Dollar',
    symbol: 'TTD',
    decimals: 2,
    format: '1,234,567.89',
    label: 'TTD - Trinidad and Tobago Dollar',
  ),
  CurrencyOption(
    code: 'TND',
    name: 'Tunisian Dinar',
    symbol: 'TND',
    decimals: 3,
    format: '1,234,567.890',
    label: 'TND - Tunisian Dinar',
  ),
  CurrencyOption(
    code: 'TRY',
    name: 'Turkish Lira',
    symbol: '₺',
    decimals: 2,
    format: '1,234,567.89',
    label: 'TRY - Turkish Lira',
  ),
  CurrencyOption(
    code: 'TMT',
    name: 'Turkmenistan New Manat',
    symbol: 'TMT',
    decimals: 2,
    format: '1,234,567.89',
    label: 'TMT - Turkmenistan New Manat',
  ),
  CurrencyOption(
    code: 'UGX',
    name: 'Uganda Shilling',
    symbol: 'UGX',
    decimals: 0,
    format: '1,234,567',
    label: 'UGX - Uganda Shilling',
  ),
  CurrencyOption(
    code: 'UAH',
    name: 'Hryvnia',
    symbol: 'UAH',
    decimals: 2,
    format: '1,234,567.89',
    label: 'UAH - Hryvnia',
  ),
  CurrencyOption(
    code: 'AED',
    name: 'UAE Dirham',
    symbol: 'AED',
    decimals: 2,
    format: '1,234,567.89',
    label: 'AED - UAE Dirham',
  ),
  CurrencyOption(
    code: 'UYU',
    name: 'Peso Uruguayo',
    symbol: 'UYU',
    decimals: 2,
    format: '1,234,567.89',
    label: 'UYU - Peso Uruguayo',
  ),
  CurrencyOption(
    code: 'UZS',
    name: 'Uzbekistan Sum',
    symbol: 'UZS',
    decimals: 2,
    format: '1,234,567.89',
    label: 'UZS - Uzbekistan Sum',
  ),
  CurrencyOption(
    code: 'VUV',
    name: 'Vatu',
    symbol: 'VUV',
    decimals: 0,
    format: '1,234,567',
    label: 'VUV - Vatu',
  ),
  CurrencyOption(
    code: 'VES',
    name: 'Bolívar Soberano',
    symbol: 'VES',
    decimals: 2,
    format: '1,234,567.89',
    label: 'VES - Bolívar Soberano',
  ),
  CurrencyOption(
    code: 'VND',
    name: 'Dong',
    symbol: '₫',
    decimals: 0,
    format: '1,234,567',
    label: 'VND - Dong',
  ),
  CurrencyOption(
    code: 'YER',
    name: 'Yemeni Rial',
    symbol: 'YER',
    decimals: 2,
    format: '1,234,567.89',
    label: 'YER - Yemeni Rial',
  ),
  CurrencyOption(
    code: 'ZMW',
    name: 'Zambian Kwacha',
    symbol: 'ZMW',
    decimals: 2,
    format: '1,234,567.89',
    label: 'ZMW - Zambian Kwacha',
  ),
  CurrencyOption(
    code: 'ZWG',
    name: 'Zimbabwe Gold',
    symbol: 'ZWG',
    decimals: 2,
    format: '1,234,567.89',
    label: 'ZWG - Zimbabwe Gold',
  ),
];
