import 'permission_actions.dart';

class PermissionDefinition {
  final String key;
  final String module;
  final String resource;
  final String action;
  final String label;
  final String description;

  const PermissionDefinition({
    required this.key,
    required this.module,
    required this.resource,
    required this.action,
    required this.label,
    required this.description,
  });
}

const Map<String, List<String>> legacyPermissionPrefixesByKey = {
  // Items + Pricing
  'item': ['items.item'],
  'composite_items': ['items.composite_item'],
  'item_groups': ['items.group'],
  'item_mapping': ['items.mapping'],
  'price_list': ['pricing.price_list'],
  'branch_price_lists': ['pricing.branch_price_list'],

  // Inventory
  'assemblies': ['inventory.assembly'],
  'inventory_adjustments': ['inventory.adjustment'],
  'picklists': ['inventory.picklist'],
  'packages': ['inventory.package'],
  'shipments': ['inventory.shipment'],
  'transfer_orders': ['inventory.transfer'],
  'move_orders': ['inventory.move'],

  // Sales
  'customers': ['sales.customer'],
  'quotations': ['sales.quotation'],
  'sales_orders': ['sales.order'],
  'invoices': ['sales.invoice'],
  'delivery_challans': ['sales.delivery_challan'],
  'customer_payments': ['sales.payment_received'],
  'sales_returns': ['sales.return'],
  'credit_notes': ['sales.credit_note'],
  'retainer_invoices': ['sales.retainer_invoice'],
  'ewaybill_perms': ['sales.eway_bill'],
  'payment_links': ['sales.payment_link'],
  'recurring_invoices': ['sales.recurring_invoice'],

  // Purchases
  'vendors': ['purchases.vendor'],
  'vendor_bank_details': ['purchases.vendor_bank_detail'],
  'expenses': ['purchases.expense'],
  'recurring_expenses': ['purchases.recurring_expense'],
  'purchase_orders': ['purchases.order'],
  'purchase_receives': ['purchases.receive'],
  'purchase_returns': ['purchases.return'],
  'bills': ['purchases.bill'],
  'recurring_bills': ['purchases.recurring_bill'],
  'vendor_payments': ['purchases.payment_made'],
  'vendor_credits': ['purchases.vendor_credit'],

  // Accountant + Accounts
  'chart_of_accounts': ['accounts.chart_of_account'],
  'manual_journals': ['accountant.manual_journal'],
  'recurring_journals': ['accountant.recurring_journal'],
  'journal_templates': ['accountant.journal_template'],
  'opening_balances': ['accountant.opening_balance'],
  'journal_entry_lines': ['accountant.journal_entry_line'],
  'bulk_update': ['accountant.bulk_update'],
  'transaction_locking': ['accountant.transaction_locking'],
  'accountant_settings': ['accountant.settings'],

  // Settings + Compliance
  'general_prefs': ['settings.organization'],
  'users': ['settings.users'],
  'branches': ['settings.branch'],
  'warehouses': ['settings.warehouse'],
  'zones': ['settings.zone'],
  'users_roles': ['settings.roles'],
  'transaction_series': ['settings.transaction_series'],

  // Reports + shell
  'dashboard_charts': ['reports.dashboard'],
  'reports': ['reports.center'],
  'audit_logs': ['reports.audit_log'],
  'documents': ['reports.document'],

  // Procurement
  'purchase_requests': ['procurement.purchase_request'],
};

const List<PermissionDefinition> permissionsRegistry = [
  // Items + Pricing
  PermissionDefinition(
    key: 'items.item.view',
    module: 'items',
    resource: 'item',
    action: PermissionActions.view,
    label: 'View Items',
    description: 'Can view items.',
  ),
  PermissionDefinition(
    key: 'items.item.create',
    module: 'items',
    resource: 'item',
    action: PermissionActions.create,
    label: 'Create Items',
    description: 'Can create items.',
  ),
  PermissionDefinition(
    key: 'items.item.edit',
    module: 'items',
    resource: 'item',
    action: PermissionActions.edit,
    label: 'Edit Items',
    description: 'Can edit items.',
  ),
  PermissionDefinition(
    key: 'items.item.delete',
    module: 'items',
    resource: 'item',
    action: PermissionActions.delete,
    label: 'Delete Items',
    description: 'Can delete items.',
  ),
  PermissionDefinition(
    key: 'items.composite_item.view',
    module: 'items',
    resource: 'composite_item',
    action: PermissionActions.view,
    label: 'View Composite Items',
    description: 'Can view composite items.',
  ),
  PermissionDefinition(
    key: 'items.composite_item.create',
    module: 'items',
    resource: 'composite_item',
    action: PermissionActions.create,
    label: 'Create Composite Items',
    description: 'Can create composite items.',
  ),
  PermissionDefinition(
    key: 'items.composite_item.edit',
    module: 'items',
    resource: 'composite_item',
    action: PermissionActions.edit,
    label: 'Edit Composite Items',
    description: 'Can edit composite items.',
  ),
  PermissionDefinition(
    key: 'items.composite_item.delete',
    module: 'items',
    resource: 'composite_item',
    action: PermissionActions.delete,
    label: 'Delete Composite Items',
    description: 'Can delete composite items.',
  ),
  PermissionDefinition(
    key: 'items.group.view',
    module: 'items',
    resource: 'group',
    action: PermissionActions.view,
    label: 'View Item Groups',
    description: 'Can view item groups.',
  ),
  PermissionDefinition(
    key: 'items.group.create',
    module: 'items',
    resource: 'group',
    action: PermissionActions.create,
    label: 'Create Item Groups',
    description: 'Can create item groups.',
  ),
  PermissionDefinition(
    key: 'items.group.edit',
    module: 'items',
    resource: 'group',
    action: PermissionActions.edit,
    label: 'Edit Item Groups',
    description: 'Can edit item groups.',
  ),
  PermissionDefinition(
    key: 'items.group.delete',
    module: 'items',
    resource: 'group',
    action: PermissionActions.delete,
    label: 'Delete Item Groups',
    description: 'Can delete item groups.',
  ),
  PermissionDefinition(
    key: 'items.mapping.view',
    module: 'items',
    resource: 'mapping',
    action: PermissionActions.view,
    label: 'View Item Mapping',
    description: 'Can view item mappings.',
  ),
  PermissionDefinition(
    key: 'items.mapping.edit',
    module: 'items',
    resource: 'mapping',
    action: PermissionActions.edit,
    label: 'Edit Item Mapping',
    description: 'Can edit item mappings.',
  ),
  PermissionDefinition(
    key: 'pricing.price_list.view',
    module: 'pricing',
    resource: 'price_list',
    action: PermissionActions.view,
    label: 'View Price Lists',
    description: 'Can view price lists.',
  ),
  PermissionDefinition(
    key: 'pricing.price_list.create',
    module: 'pricing',
    resource: 'price_list',
    action: PermissionActions.create,
    label: 'Create Price Lists',
    description: 'Can create price lists.',
  ),
  PermissionDefinition(
    key: 'pricing.price_list.edit',
    module: 'pricing',
    resource: 'price_list',
    action: PermissionActions.edit,
    label: 'Edit Price Lists',
    description: 'Can edit price lists.',
  ),
  PermissionDefinition(
    key: 'pricing.price_list.delete',
    module: 'pricing',
    resource: 'price_list',
    action: PermissionActions.delete,
    label: 'Delete Price Lists',
    description: 'Can delete price lists.',
  ),
  PermissionDefinition(
    key: 'pricing.branch_price_list.view',
    module: 'pricing',
    resource: 'branch_price_list',
    action: PermissionActions.view,
    label: 'View Branch Price Lists',
    description: 'Can view branch price lists.',
  ),
  PermissionDefinition(
    key: 'pricing.branch_price_list.create',
    module: 'pricing',
    resource: 'branch_price_list',
    action: PermissionActions.create,
    label: 'Create Branch Price Lists',
    description: 'Can create branch price lists.',
  ),
  PermissionDefinition(
    key: 'pricing.branch_price_list.edit',
    module: 'pricing',
    resource: 'branch_price_list',
    action: PermissionActions.edit,
    label: 'Edit Branch Price Lists',
    description: 'Can edit branch price lists.',
  ),
  PermissionDefinition(
    key: 'pricing.branch_price_list.delete',
    module: 'pricing',
    resource: 'branch_price_list',
    action: PermissionActions.delete,
    label: 'Delete Branch Price Lists',
    description: 'Can delete branch price lists.',
  ),

  // Inventory
  PermissionDefinition(
    key: 'inventory.assembly.view',
    module: 'inventory',
    resource: 'assembly',
    action: PermissionActions.view,
    label: 'View Assemblies',
    description: 'Can view assemblies.',
  ),
  PermissionDefinition(
    key: 'inventory.assembly.create',
    module: 'inventory',
    resource: 'assembly',
    action: PermissionActions.create,
    label: 'Create Assemblies',
    description: 'Can create assemblies.',
  ),
  PermissionDefinition(
    key: 'inventory.assembly.edit',
    module: 'inventory',
    resource: 'assembly',
    action: PermissionActions.edit,
    label: 'Edit Assemblies',
    description: 'Can edit assemblies.',
  ),
  PermissionDefinition(
    key: 'inventory.assembly.delete',
    module: 'inventory',
    resource: 'assembly',
    action: PermissionActions.delete,
    label: 'Delete Assemblies',
    description: 'Can delete assemblies.',
  ),
  PermissionDefinition(
    key: 'inventory.adjustment.view',
    module: 'inventory',
    resource: 'adjustment',
    action: PermissionActions.view,
    label: 'View Inventory Adjustments',
    description: 'Can view inventory adjustments.',
  ),
  PermissionDefinition(
    key: 'inventory.adjustment.create',
    module: 'inventory',
    resource: 'adjustment',
    action: PermissionActions.create,
    label: 'Create Inventory Adjustments',
    description: 'Can create inventory adjustments.',
  ),
  PermissionDefinition(
    key: 'inventory.adjustment.edit',
    module: 'inventory',
    resource: 'adjustment',
    action: PermissionActions.edit,
    label: 'Edit Inventory Adjustments',
    description: 'Can edit inventory adjustments.',
  ),
  PermissionDefinition(
    key: 'inventory.adjustment.delete',
    module: 'inventory',
    resource: 'adjustment',
    action: PermissionActions.delete,
    label: 'Delete Inventory Adjustments',
    description: 'Can delete inventory adjustments.',
  ),
  PermissionDefinition(
    key: 'inventory.picklist.view',
    module: 'inventory',
    resource: 'picklist',
    action: PermissionActions.view,
    label: 'View Picklists',
    description: 'Can view picklists.',
  ),
  PermissionDefinition(
    key: 'inventory.picklist.create',
    module: 'inventory',
    resource: 'picklist',
    action: PermissionActions.create,
    label: 'Create Picklists',
    description: 'Can create picklists.',
  ),
  PermissionDefinition(
    key: 'inventory.picklist.edit',
    module: 'inventory',
    resource: 'picklist',
    action: PermissionActions.edit,
    label: 'Edit Picklists',
    description: 'Can edit picklists.',
  ),
  PermissionDefinition(
    key: 'inventory.picklist.delete',
    module: 'inventory',
    resource: 'picklist',
    action: PermissionActions.delete,
    label: 'Delete Picklists',
    description: 'Can delete picklists.',
  ),
  PermissionDefinition(
    key: 'inventory.package.view',
    module: 'inventory',
    resource: 'package',
    action: PermissionActions.view,
    label: 'View Packages',
    description: 'Can view packages.',
  ),
  PermissionDefinition(
    key: 'inventory.package.create',
    module: 'inventory',
    resource: 'package',
    action: PermissionActions.create,
    label: 'Create Packages',
    description: 'Can create packages.',
  ),
  PermissionDefinition(
    key: 'inventory.package.edit',
    module: 'inventory',
    resource: 'package',
    action: PermissionActions.edit,
    label: 'Edit Packages',
    description: 'Can edit packages.',
  ),
  PermissionDefinition(
    key: 'inventory.package.delete',
    module: 'inventory',
    resource: 'package',
    action: PermissionActions.delete,
    label: 'Delete Packages',
    description: 'Can delete packages.',
  ),
  PermissionDefinition(
    key: 'inventory.shipment.view',
    module: 'inventory',
    resource: 'shipment',
    action: PermissionActions.view,
    label: 'View Shipments',
    description: 'Can view shipments.',
  ),
  PermissionDefinition(
    key: 'inventory.shipment.create',
    module: 'inventory',
    resource: 'shipment',
    action: PermissionActions.create,
    label: 'Create Shipments',
    description: 'Can create shipments.',
  ),
  PermissionDefinition(
    key: 'inventory.shipment.edit',
    module: 'inventory',
    resource: 'shipment',
    action: PermissionActions.edit,
    label: 'Edit Shipments',
    description: 'Can edit shipments.',
  ),
  PermissionDefinition(
    key: 'inventory.shipment.delete',
    module: 'inventory',
    resource: 'shipment',
    action: PermissionActions.delete,
    label: 'Delete Shipments',
    description: 'Can delete shipments.',
  ),
  PermissionDefinition(
    key: 'inventory.transfer.view',
    module: 'inventory',
    resource: 'transfer',
    action: PermissionActions.view,
    label: 'View Transfer Orders',
    description: 'Can view transfer orders.',
  ),
  PermissionDefinition(
    key: 'inventory.transfer.create',
    module: 'inventory',
    resource: 'transfer',
    action: PermissionActions.create,
    label: 'Create Transfer Orders',
    description: 'Can create transfer orders.',
  ),
  PermissionDefinition(
    key: 'inventory.transfer.edit',
    module: 'inventory',
    resource: 'transfer',
    action: PermissionActions.edit,
    label: 'Edit Transfer Orders',
    description: 'Can edit transfer orders.',
  ),
  PermissionDefinition(
    key: 'inventory.transfer.delete',
    module: 'inventory',
    resource: 'transfer',
    action: PermissionActions.delete,
    label: 'Delete Transfer Orders',
    description: 'Can delete transfer orders.',
  ),
  PermissionDefinition(
    key: 'inventory.transfer.approve',
    module: 'inventory',
    resource: 'transfer',
    action: PermissionActions.approve,
    label: 'Approve Transfer Orders',
    description: 'Can approve transfer orders.',
  ),
  PermissionDefinition(
    key: 'inventory.move.view',
    module: 'inventory',
    resource: 'move',
    action: PermissionActions.view,
    label: 'View Move Orders',
    description: 'Can view move orders.',
  ),
  PermissionDefinition(
    key: 'inventory.move.create',
    module: 'inventory',
    resource: 'move',
    action: PermissionActions.create,
    label: 'Create Move Orders',
    description: 'Can create move orders.',
  ),
  PermissionDefinition(
    key: 'inventory.move.edit',
    module: 'inventory',
    resource: 'move',
    action: PermissionActions.edit,
    label: 'Edit Move Orders',
    description: 'Can edit move orders.',
  ),
  PermissionDefinition(
    key: 'inventory.move.delete',
    module: 'inventory',
    resource: 'move',
    action: PermissionActions.delete,
    label: 'Delete Move Orders',
    description: 'Can delete move orders.',
  ),
  PermissionDefinition(
    key: 'inventory.move.approve',
    module: 'inventory',
    resource: 'move',
    action: PermissionActions.approve,
    label: 'Approve Move Orders',
    description: 'Can approve move orders.',
  ),

  // Sales
  PermissionDefinition(
    key: 'sales.customer.view',
    module: 'sales',
    resource: 'customer',
    action: PermissionActions.view,
    label: 'View Customers',
    description: 'Can view customers.',
  ),
  PermissionDefinition(
    key: 'sales.customer.create',
    module: 'sales',
    resource: 'customer',
    action: PermissionActions.create,
    label: 'Create Customers',
    description: 'Can create customers.',
  ),
  PermissionDefinition(
    key: 'sales.customer.edit',
    module: 'sales',
    resource: 'customer',
    action: PermissionActions.edit,
    label: 'Edit Customers',
    description: 'Can edit customers.',
  ),
  PermissionDefinition(
    key: 'sales.customer.delete',
    module: 'sales',
    resource: 'customer',
    action: PermissionActions.delete,
    label: 'Delete Customers',
    description: 'Can delete customers.',
  ),
  PermissionDefinition(
    key: 'sales.quotation.view',
    module: 'sales',
    resource: 'quotation',
    action: PermissionActions.view,
    label: 'View Quotations',
    description: 'Can view quotations.',
  ),
  PermissionDefinition(
    key: 'sales.quotation.create',
    module: 'sales',
    resource: 'quotation',
    action: PermissionActions.create,
    label: 'Create Quotations',
    description: 'Can create quotations.',
  ),
  PermissionDefinition(
    key: 'sales.quotation.edit',
    module: 'sales',
    resource: 'quotation',
    action: PermissionActions.edit,
    label: 'Edit Quotations',
    description: 'Can edit quotations.',
  ),
  PermissionDefinition(
    key: 'sales.quotation.delete',
    module: 'sales',
    resource: 'quotation',
    action: PermissionActions.delete,
    label: 'Delete Quotations',
    description: 'Can delete quotations.',
  ),
  PermissionDefinition(
    key: 'sales.order.view',
    module: 'sales',
    resource: 'order',
    action: PermissionActions.view,
    label: 'View Sales Orders',
    description: 'Can view sales orders.',
  ),
  PermissionDefinition(
    key: 'sales.order.create',
    module: 'sales',
    resource: 'order',
    action: PermissionActions.create,
    label: 'Create Sales Orders',
    description: 'Can create sales orders.',
  ),
  PermissionDefinition(
    key: 'sales.order.edit',
    module: 'sales',
    resource: 'order',
    action: PermissionActions.edit,
    label: 'Edit Sales Orders',
    description: 'Can edit sales orders.',
  ),
  PermissionDefinition(
    key: 'sales.order.delete',
    module: 'sales',
    resource: 'order',
    action: PermissionActions.delete,
    label: 'Delete Sales Orders',
    description: 'Can delete sales orders.',
  ),
  PermissionDefinition(
    key: 'sales.invoice.view',
    module: 'sales',
    resource: 'invoice',
    action: PermissionActions.view,
    label: 'View Invoices',
    description: 'Can view invoices.',
  ),
  PermissionDefinition(
    key: 'sales.invoice.create',
    module: 'sales',
    resource: 'invoice',
    action: PermissionActions.create,
    label: 'Create Invoices',
    description: 'Can create invoices.',
  ),
  PermissionDefinition(
    key: 'sales.invoice.edit',
    module: 'sales',
    resource: 'invoice',
    action: PermissionActions.edit,
    label: 'Edit Invoices',
    description: 'Can edit invoices.',
  ),
  PermissionDefinition(
    key: 'sales.invoice.delete',
    module: 'sales',
    resource: 'invoice',
    action: PermissionActions.delete,
    label: 'Delete Invoices',
    description: 'Can delete invoices.',
  ),
  PermissionDefinition(
    key: 'sales.delivery_challan.view',
    module: 'sales',
    resource: 'delivery_challan',
    action: PermissionActions.view,
    label: 'View Delivery Challans',
    description: 'Can view delivery challans.',
  ),
  PermissionDefinition(
    key: 'sales.delivery_challan.create',
    module: 'sales',
    resource: 'delivery_challan',
    action: PermissionActions.create,
    label: 'Create Delivery Challans',
    description: 'Can create delivery challans.',
  ),
  PermissionDefinition(
    key: 'sales.delivery_challan.edit',
    module: 'sales',
    resource: 'delivery_challan',
    action: PermissionActions.edit,
    label: 'Edit Delivery Challans',
    description: 'Can edit delivery challans.',
  ),
  PermissionDefinition(
    key: 'sales.delivery_challan.delete',
    module: 'sales',
    resource: 'delivery_challan',
    action: PermissionActions.delete,
    label: 'Delete Delivery Challans',
    description: 'Can delete delivery challans.',
  ),
  PermissionDefinition(
    key: 'sales.payment_received.view',
    module: 'sales',
    resource: 'payment_received',
    action: PermissionActions.view,
    label: 'View Payments Received',
    description: 'Can view payments received.',
  ),
  PermissionDefinition(
    key: 'sales.payment_received.create',
    module: 'sales',
    resource: 'payment_received',
    action: PermissionActions.create,
    label: 'Create Payments Received',
    description: 'Can create payments received.',
  ),
  PermissionDefinition(
    key: 'sales.payment_received.edit',
    module: 'sales',
    resource: 'payment_received',
    action: PermissionActions.edit,
    label: 'Edit Payments Received',
    description: 'Can edit payments received.',
  ),
  PermissionDefinition(
    key: 'sales.payment_received.delete',
    module: 'sales',
    resource: 'payment_received',
    action: PermissionActions.delete,
    label: 'Delete Payments Received',
    description: 'Can delete payments received.',
  ),
  PermissionDefinition(
    key: 'sales.return.view',
    module: 'sales',
    resource: 'return',
    action: PermissionActions.view,
    label: 'View Sales Returns',
    description: 'Can view sales returns.',
  ),
  PermissionDefinition(
    key: 'sales.return.create',
    module: 'sales',
    resource: 'return',
    action: PermissionActions.create,
    label: 'Create Sales Returns',
    description: 'Can create sales returns.',
  ),
  PermissionDefinition(
    key: 'sales.return.edit',
    module: 'sales',
    resource: 'return',
    action: PermissionActions.edit,
    label: 'Edit Sales Returns',
    description: 'Can edit sales returns.',
  ),
  PermissionDefinition(
    key: 'sales.return.delete',
    module: 'sales',
    resource: 'return',
    action: PermissionActions.delete,
    label: 'Delete Sales Returns',
    description: 'Can delete sales returns.',
  ),
  PermissionDefinition(
    key: 'sales.credit_note.view',
    module: 'sales',
    resource: 'credit_note',
    action: PermissionActions.view,
    label: 'View Credit Notes',
    description: 'Can view credit notes.',
  ),
  PermissionDefinition(
    key: 'sales.credit_note.create',
    module: 'sales',
    resource: 'credit_note',
    action: PermissionActions.create,
    label: 'Create Credit Notes',
    description: 'Can create credit notes.',
  ),
  PermissionDefinition(
    key: 'sales.credit_note.edit',
    module: 'sales',
    resource: 'credit_note',
    action: PermissionActions.edit,
    label: 'Edit Credit Notes',
    description: 'Can edit credit notes.',
  ),
  PermissionDefinition(
    key: 'sales.credit_note.delete',
    module: 'sales',
    resource: 'credit_note',
    action: PermissionActions.delete,
    label: 'Delete Credit Notes',
    description: 'Can delete credit notes.',
  ),
  PermissionDefinition(
    key: 'sales.retainer_invoice.view',
    module: 'sales',
    resource: 'retainer_invoice',
    action: PermissionActions.view,
    label: 'View Retainer Invoices',
    description: 'Can view retainer invoices.',
  ),
  PermissionDefinition(
    key: 'sales.retainer_invoice.create',
    module: 'sales',
    resource: 'retainer_invoice',
    action: PermissionActions.create,
    label: 'Create Retainer Invoices',
    description: 'Can create retainer invoices.',
  ),
  PermissionDefinition(
    key: 'sales.retainer_invoice.edit',
    module: 'sales',
    resource: 'retainer_invoice',
    action: PermissionActions.edit,
    label: 'Edit Retainer Invoices',
    description: 'Can edit retainer invoices.',
  ),
  PermissionDefinition(
    key: 'sales.retainer_invoice.delete',
    module: 'sales',
    resource: 'retainer_invoice',
    action: PermissionActions.delete,
    label: 'Delete Retainer Invoices',
    description: 'Can delete retainer invoices.',
  ),
  PermissionDefinition(
    key: 'sales.eway_bill.view',
    module: 'sales',
    resource: 'eway_bill',
    action: PermissionActions.view,
    label: 'View e-Way Bills',
    description: 'Can view e-way bills.',
  ),
  PermissionDefinition(
    key: 'sales.eway_bill.create',
    module: 'sales',
    resource: 'eway_bill',
    action: PermissionActions.create,
    label: 'Create e-Way Bills',
    description: 'Can create e-way bills.',
  ),
  PermissionDefinition(
    key: 'sales.eway_bill.delete',
    module: 'sales',
    resource: 'eway_bill',
    action: PermissionActions.delete,
    label: 'Delete e-Way Bills',
    description: 'Can delete e-way bills.',
  ),
  PermissionDefinition(
    key: 'sales.payment_link.view',
    module: 'sales',
    resource: 'payment_link',
    action: PermissionActions.view,
    label: 'View Payment Links',
    description: 'Can view payment links.',
  ),
  PermissionDefinition(
    key: 'sales.payment_link.create',
    module: 'sales',
    resource: 'payment_link',
    action: PermissionActions.create,
    label: 'Create Payment Links',
    description: 'Can create payment links.',
  ),
  PermissionDefinition(
    key: 'sales.payment_link.delete',
    module: 'sales',
    resource: 'payment_link',
    action: PermissionActions.delete,
    label: 'Delete Payment Links',
    description: 'Can delete payment links.',
  ),
  PermissionDefinition(
    key: 'sales.recurring_invoice.view',
    module: 'sales',
    resource: 'recurring_invoice',
    action: PermissionActions.view,
    label: 'View Recurring Invoices',
    description: 'Can view recurring invoices.',
  ),
  PermissionDefinition(
    key: 'sales.recurring_invoice.create',
    module: 'sales',
    resource: 'recurring_invoice',
    action: PermissionActions.create,
    label: 'Create Recurring Invoices',
    description: 'Can create recurring invoices.',
  ),
  PermissionDefinition(
    key: 'sales.recurring_invoice.edit',
    module: 'sales',
    resource: 'recurring_invoice',
    action: PermissionActions.edit,
    label: 'Edit Recurring Invoices',
    description: 'Can edit recurring invoices.',
  ),
  PermissionDefinition(
    key: 'sales.recurring_invoice.delete',
    module: 'sales',
    resource: 'recurring_invoice',
    action: PermissionActions.delete,
    label: 'Delete Recurring Invoices',
    description: 'Can delete recurring invoices.',
  ),

  // Purchases
  PermissionDefinition(
    key: 'purchases.vendor.view',
    module: 'purchases',
    resource: 'vendor',
    action: PermissionActions.view,
    label: 'View Vendors',
    description: 'Can view vendors.',
  ),
  PermissionDefinition(
    key: 'purchases.vendor.create',
    module: 'purchases',
    resource: 'vendor',
    action: PermissionActions.create,
    label: 'Create Vendors',
    description: 'Can create vendors.',
  ),
  PermissionDefinition(
    key: 'purchases.vendor.edit',
    module: 'purchases',
    resource: 'vendor',
    action: PermissionActions.edit,
    label: 'Edit Vendors',
    description: 'Can edit vendors.',
  ),
  PermissionDefinition(
    key: 'purchases.vendor.delete',
    module: 'purchases',
    resource: 'vendor',
    action: PermissionActions.delete,
    label: 'Delete Vendors',
    description: 'Can delete vendors.',
  ),
  PermissionDefinition(
    key: 'purchases.expense.view',
    module: 'purchases',
    resource: 'expense',
    action: PermissionActions.view,
    label: 'View Expenses',
    description: 'Can view expenses.',
  ),
  PermissionDefinition(
    key: 'purchases.expense.create',
    module: 'purchases',
    resource: 'expense',
    action: PermissionActions.create,
    label: 'Create Expenses',
    description: 'Can create expenses.',
  ),
  PermissionDefinition(
    key: 'purchases.expense.edit',
    module: 'purchases',
    resource: 'expense',
    action: PermissionActions.edit,
    label: 'Edit Expenses',
    description: 'Can edit expenses.',
  ),
  PermissionDefinition(
    key: 'purchases.expense.delete',
    module: 'purchases',
    resource: 'expense',
    action: PermissionActions.delete,
    label: 'Delete Expenses',
    description: 'Can delete expenses.',
  ),
  PermissionDefinition(
    key: 'purchases.recurring_expense.view',
    module: 'purchases',
    resource: 'recurring_expense',
    action: PermissionActions.view,
    label: 'View Recurring Expenses',
    description: 'Can view recurring expenses.',
  ),
  PermissionDefinition(
    key: 'purchases.recurring_expense.create',
    module: 'purchases',
    resource: 'recurring_expense',
    action: PermissionActions.create,
    label: 'Create Recurring Expenses',
    description: 'Can create recurring expenses.',
  ),
  PermissionDefinition(
    key: 'purchases.recurring_expense.edit',
    module: 'purchases',
    resource: 'recurring_expense',
    action: PermissionActions.edit,
    label: 'Edit Recurring Expenses',
    description: 'Can edit recurring expenses.',
  ),
  PermissionDefinition(
    key: 'purchases.recurring_expense.delete',
    module: 'purchases',
    resource: 'recurring_expense',
    action: PermissionActions.delete,
    label: 'Delete Recurring Expenses',
    description: 'Can delete recurring expenses.',
  ),
  PermissionDefinition(
    key: 'purchases.order.view',
    module: 'purchases',
    resource: 'order',
    action: PermissionActions.view,
    label: 'View Purchase Orders',
    description: 'Can view purchase orders.',
  ),
  PermissionDefinition(
    key: 'purchases.order.create',
    module: 'purchases',
    resource: 'order',
    action: PermissionActions.create,
    label: 'Create Purchase Orders',
    description: 'Can create purchase orders.',
  ),
  PermissionDefinition(
    key: 'purchases.order.edit',
    module: 'purchases',
    resource: 'order',
    action: PermissionActions.edit,
    label: 'Edit Purchase Orders',
    description: 'Can edit purchase orders.',
  ),
  PermissionDefinition(
    key: 'purchases.order.delete',
    module: 'purchases',
    resource: 'order',
    action: PermissionActions.delete,
    label: 'Delete Purchase Orders',
    description: 'Can delete purchase orders.',
  ),
  PermissionDefinition(
    key: 'purchases.receive.view',
    module: 'purchases',
    resource: 'receive',
    action: PermissionActions.view,
    label: 'View Purchase Receives',
    description: 'Can view purchase receives.',
  ),
  PermissionDefinition(
    key: 'purchases.receive.create',
    module: 'purchases',
    resource: 'receive',
    action: PermissionActions.create,
    label: 'Create Purchase Receives',
    description: 'Can create purchase receives.',
  ),
  PermissionDefinition(
    key: 'purchases.receive.delete',
    module: 'purchases',
    resource: 'receive',
    action: PermissionActions.delete,
    label: 'Delete Purchase Receives',
    description: 'Can delete purchase receives.',
  ),
  PermissionDefinition(
    key: 'purchases.bill.view',
    module: 'purchases',
    resource: 'bill',
    action: PermissionActions.view,
    label: 'View Bills',
    description: 'Can view bills.',
  ),
  PermissionDefinition(
    key: 'purchases.bill.create',
    module: 'purchases',
    resource: 'bill',
    action: PermissionActions.create,
    label: 'Create Bills',
    description: 'Can create bills.',
  ),
  PermissionDefinition(
    key: 'purchases.bill.edit',
    module: 'purchases',
    resource: 'bill',
    action: PermissionActions.edit,
    label: 'Edit Bills',
    description: 'Can edit bills.',
  ),
  PermissionDefinition(
    key: 'purchases.bill.delete',
    module: 'purchases',
    resource: 'bill',
    action: PermissionActions.delete,
    label: 'Delete Bills',
    description: 'Can delete bills.',
  ),
  PermissionDefinition(
    key: 'purchases.recurring_bill.view',
    module: 'purchases',
    resource: 'recurring_bill',
    action: PermissionActions.view,
    label: 'View Recurring Bills',
    description: 'Can view recurring bills.',
  ),
  PermissionDefinition(
    key: 'purchases.recurring_bill.create',
    module: 'purchases',
    resource: 'recurring_bill',
    action: PermissionActions.create,
    label: 'Create Recurring Bills',
    description: 'Can create recurring bills.',
  ),
  PermissionDefinition(
    key: 'purchases.recurring_bill.edit',
    module: 'purchases',
    resource: 'recurring_bill',
    action: PermissionActions.edit,
    label: 'Edit Recurring Bills',
    description: 'Can edit recurring bills.',
  ),
  PermissionDefinition(
    key: 'purchases.recurring_bill.delete',
    module: 'purchases',
    resource: 'recurring_bill',
    action: PermissionActions.delete,
    label: 'Delete Recurring Bills',
    description: 'Can delete recurring bills.',
  ),
  PermissionDefinition(
    key: 'purchases.payment_made.view',
    module: 'purchases',
    resource: 'payment_made',
    action: PermissionActions.view,
    label: 'View Payments Made',
    description: 'Can view payments made.',
  ),
  PermissionDefinition(
    key: 'purchases.payment_made.create',
    module: 'purchases',
    resource: 'payment_made',
    action: PermissionActions.create,
    label: 'Create Payments Made',
    description: 'Can create payments made.',
  ),
  PermissionDefinition(
    key: 'purchases.payment_made.edit',
    module: 'purchases',
    resource: 'payment_made',
    action: PermissionActions.edit,
    label: 'Edit Payments Made',
    description: 'Can edit payments made.',
  ),
  PermissionDefinition(
    key: 'purchases.payment_made.delete',
    module: 'purchases',
    resource: 'payment_made',
    action: PermissionActions.delete,
    label: 'Delete Payments Made',
    description: 'Can delete payments made.',
  ),
  PermissionDefinition(
    key: 'purchases.vendor_credit.view',
    module: 'purchases',
    resource: 'vendor_credit',
    action: PermissionActions.view,
    label: 'View Vendor Credits',
    description: 'Can view vendor credits.',
  ),
  PermissionDefinition(
    key: 'purchases.vendor_credit.create',
    module: 'purchases',
    resource: 'vendor_credit',
    action: PermissionActions.create,
    label: 'Create Vendor Credits',
    description: 'Can create vendor credits.',
  ),
  PermissionDefinition(
    key: 'purchases.vendor_credit.edit',
    module: 'purchases',
    resource: 'vendor_credit',
    action: PermissionActions.edit,
    label: 'Edit Vendor Credits',
    description: 'Can edit vendor credits.',
  ),
  PermissionDefinition(
    key: 'purchases.vendor_credit.delete',
    module: 'purchases',
    resource: 'vendor_credit',
    action: PermissionActions.delete,
    label: 'Delete Vendor Credits',
    description: 'Can delete vendor credits.',
  ),

  // Accounts + Accountant
  PermissionDefinition(
    key: 'accounts.chart_of_account.view',
    module: 'accounts',
    resource: 'chart_of_account',
    action: PermissionActions.view,
    label: 'View Chart of Accounts',
    description: 'Can view chart of accounts.',
  ),
  PermissionDefinition(
    key: 'accounts.chart_of_account.create',
    module: 'accounts',
    resource: 'chart_of_account',
    action: PermissionActions.create,
    label: 'Create Chart of Accounts',
    description: 'Can create chart of accounts.',
  ),
  PermissionDefinition(
    key: 'accounts.chart_of_account.edit',
    module: 'accounts',
    resource: 'chart_of_account',
    action: PermissionActions.edit,
    label: 'Edit Chart of Accounts',
    description: 'Can edit chart of accounts.',
  ),
  PermissionDefinition(
    key: 'accounts.chart_of_account.delete',
    module: 'accounts',
    resource: 'chart_of_account',
    action: PermissionActions.delete,
    label: 'Delete Chart of Accounts',
    description: 'Can delete chart of accounts.',
  ),
  PermissionDefinition(
    key: 'accountant.manual_journal.view',
    module: 'accountant',
    resource: 'manual_journal',
    action: PermissionActions.view,
    label: 'View Manual Journals',
    description: 'Can view manual journals.',
  ),
  PermissionDefinition(
    key: 'accountant.manual_journal.create',
    module: 'accountant',
    resource: 'manual_journal',
    action: PermissionActions.create,
    label: 'Create Manual Journals',
    description: 'Can create manual journals.',
  ),
  PermissionDefinition(
    key: 'accountant.manual_journal.edit',
    module: 'accountant',
    resource: 'manual_journal',
    action: PermissionActions.edit,
    label: 'Edit Manual Journals',
    description: 'Can edit manual journals.',
  ),
  PermissionDefinition(
    key: 'accountant.manual_journal.delete',
    module: 'accountant',
    resource: 'manual_journal',
    action: PermissionActions.delete,
    label: 'Delete Manual Journals',
    description: 'Can delete manual journals.',
  ),
  PermissionDefinition(
    key: 'accountant.recurring_journal.view',
    module: 'accountant',
    resource: 'recurring_journal',
    action: PermissionActions.view,
    label: 'View Recurring Journals',
    description: 'Can view recurring journals.',
  ),
  PermissionDefinition(
    key: 'accountant.recurring_journal.create',
    module: 'accountant',
    resource: 'recurring_journal',
    action: PermissionActions.create,
    label: 'Create Recurring Journals',
    description: 'Can create recurring journals.',
  ),
  PermissionDefinition(
    key: 'accountant.recurring_journal.edit',
    module: 'accountant',
    resource: 'recurring_journal',
    action: PermissionActions.edit,
    label: 'Edit Recurring Journals',
    description: 'Can edit recurring journals.',
  ),
  PermissionDefinition(
    key: 'accountant.recurring_journal.delete',
    module: 'accountant',
    resource: 'recurring_journal',
    action: PermissionActions.delete,
    label: 'Delete Recurring Journals',
    description: 'Can delete recurring journals.',
  ),
  PermissionDefinition(
    key: 'accountant.bulk_update.view',
    module: 'accountant',
    resource: 'bulk_update',
    action: PermissionActions.view,
    label: 'View Bulk Update',
    description: 'Can view bulk update.',
  ),
  PermissionDefinition(
    key: 'accountant.bulk_update.edit',
    module: 'accountant',
    resource: 'bulk_update',
    action: PermissionActions.edit,
    label: 'Edit Bulk Update',
    description: 'Can use bulk update.',
  ),
  PermissionDefinition(
    key: 'accountant.transaction_locking.view',
    module: 'accountant',
    resource: 'transaction_locking',
    action: PermissionActions.view,
    label: 'View Transaction Locking',
    description: 'Can view transaction locking.',
  ),
  PermissionDefinition(
    key: 'accountant.transaction_locking.edit',
    module: 'accountant',
    resource: 'transaction_locking',
    action: PermissionActions.edit,
    label: 'Edit Transaction Locking',
    description: 'Can edit transaction locking.',
  ),
  PermissionDefinition(
    key: 'accountant.opening_balance.view',
    module: 'accountant',
    resource: 'opening_balance',
    action: PermissionActions.view,
    label: 'View Opening Balances',
    description: 'Can view opening balances.',
  ),
  PermissionDefinition(
    key: 'accountant.opening_balance.edit',
    module: 'accountant',
    resource: 'opening_balance',
    action: PermissionActions.edit,
    label: 'Edit Opening Balances',
    description: 'Can edit opening balances.',
  ),
  PermissionDefinition(
    key: 'accountant.journal_template.view',
    module: 'accountant',
    resource: 'journal_template',
    action: PermissionActions.view,
    label: 'View Journal Templates',
    description: 'Can view journal templates.',
  ),
  PermissionDefinition(
    key: 'accountant.journal_template.create',
    module: 'accountant',
    resource: 'journal_template',
    action: PermissionActions.create,
    label: 'Create Journal Templates',
    description: 'Can create journal templates.',
  ),
  PermissionDefinition(
    key: 'accountant.journal_template.edit',
    module: 'accountant',
    resource: 'journal_template',
    action: PermissionActions.edit,
    label: 'Edit Journal Templates',
    description: 'Can edit journal templates.',
  ),
  PermissionDefinition(
    key: 'accountant.journal_template.delete',
    module: 'accountant',
    resource: 'journal_template',
    action: PermissionActions.delete,
    label: 'Delete Journal Templates',
    description: 'Can delete journal templates.',
  ),
  PermissionDefinition(
    key: 'accountant.journal_entry_line.view',
    module: 'accountant',
    resource: 'journal_entry_line',
    action: PermissionActions.view,
    label: 'View Journal Entry Lines',
    description: 'Can view journal entry lines.',
  ),
  PermissionDefinition(
    key: 'accountant.journal_entry_line.export',
    module: 'accountant',
    resource: 'journal_entry_line',
    action: PermissionActions.export,
    label: 'Export Journal Entry Lines',
    description: 'Can export journal entry lines.',
  ),
  PermissionDefinition(
    key: 'accountant.settings.view',
    module: 'accountant',
    resource: 'settings',
    action: PermissionActions.view,
    label: 'View Accountant Settings',
    description: 'Can view accountant settings.',
  ),
  PermissionDefinition(
    key: 'accountant.settings.edit',
    module: 'accountant',
    resource: 'settings',
    action: PermissionActions.edit,
    label: 'Edit Accountant Settings',
    description: 'Can edit accountant settings.',
  ),

  // Settings + reports/shell
  PermissionDefinition(
    key: 'settings.organization.view',
    module: 'settings',
    resource: 'organization',
    action: PermissionActions.view,
    label: 'View Organization Settings',
    description: 'Can view organization settings.',
  ),
  PermissionDefinition(
    key: 'settings.organization.edit',
    module: 'settings',
    resource: 'organization',
    action: PermissionActions.edit,
    label: 'Edit Organization Settings',
    description: 'Can edit organization settings.',
  ),
  PermissionDefinition(
    key: 'settings.branch.view',
    module: 'settings',
    resource: 'branch',
    action: PermissionActions.view,
    label: 'View Branches',
    description: 'Can view branches.',
  ),
  PermissionDefinition(
    key: 'settings.branch.create',
    module: 'settings',
    resource: 'branch',
    action: PermissionActions.create,
    label: 'Create Branches',
    description: 'Can create branches.',
  ),
  PermissionDefinition(
    key: 'settings.branch.edit',
    module: 'settings',
    resource: 'branch',
    action: PermissionActions.edit,
    label: 'Edit Branches',
    description: 'Can edit branches.',
  ),
  PermissionDefinition(
    key: 'settings.branch.delete',
    module: 'settings',
    resource: 'branch',
    action: PermissionActions.delete,
    label: 'Delete Branches',
    description: 'Can delete branches.',
  ),
  PermissionDefinition(
    key: 'settings.warehouse.view',
    module: 'settings',
    resource: 'warehouse',
    action: PermissionActions.view,
    label: 'View Warehouses',
    description: 'Can view warehouses.',
  ),
  PermissionDefinition(
    key: 'settings.warehouse.create',
    module: 'settings',
    resource: 'warehouse',
    action: PermissionActions.create,
    label: 'Create Warehouses',
    description: 'Can create warehouses.',
  ),
  PermissionDefinition(
    key: 'settings.warehouse.edit',
    module: 'settings',
    resource: 'warehouse',
    action: PermissionActions.edit,
    label: 'Edit Warehouses',
    description: 'Can edit warehouses.',
  ),
  PermissionDefinition(
    key: 'settings.warehouse.delete',
    module: 'settings',
    resource: 'warehouse',
    action: PermissionActions.delete,
    label: 'Delete Warehouses',
    description: 'Can delete warehouses.',
  ),
  PermissionDefinition(
    key: 'settings.zone.view',
    module: 'settings',
    resource: 'zone',
    action: PermissionActions.view,
    label: 'View Zones and Bins',
    description: 'Can view zones and bins.',
  ),
  PermissionDefinition(
    key: 'settings.zone.create',
    module: 'settings',
    resource: 'zone',
    action: PermissionActions.create,
    label: 'Create Zones and Bins',
    description: 'Can create zones and bins.',
  ),
  PermissionDefinition(
    key: 'settings.zone.edit',
    module: 'settings',
    resource: 'zone',
    action: PermissionActions.edit,
    label: 'Edit Zones and Bins',
    description: 'Can edit zones and bins.',
  ),
  PermissionDefinition(
    key: 'settings.zone.delete',
    module: 'settings',
    resource: 'zone',
    action: PermissionActions.delete,
    label: 'Delete Zones and Bins',
    description: 'Can delete zones and bins.',
  ),
  PermissionDefinition(
    key: 'settings.users.view',
    module: 'settings',
    resource: 'users',
    action: PermissionActions.view,
    label: 'View Users',
    description: 'Can view users.',
  ),
  PermissionDefinition(
    key: 'settings.users.create',
    module: 'settings',
    resource: 'users',
    action: PermissionActions.create,
    label: 'Create Users',
    description: 'Can create users.',
  ),
  PermissionDefinition(
    key: 'settings.users.edit',
    module: 'settings',
    resource: 'users',
    action: PermissionActions.edit,
    label: 'Edit Users',
    description: 'Can edit users.',
  ),
  PermissionDefinition(
    key: 'settings.users.delete',
    module: 'settings',
    resource: 'users',
    action: PermissionActions.delete,
    label: 'Delete Users',
    description: 'Can delete users.',
  ),
  PermissionDefinition(
    key: 'settings.roles.view',
    module: 'settings',
    resource: 'roles',
    action: PermissionActions.view,
    label: 'View Roles',
    description: 'Can view roles.',
  ),
  PermissionDefinition(
    key: 'settings.roles.create',
    module: 'settings',
    resource: 'roles',
    action: PermissionActions.create,
    label: 'Create Roles',
    description: 'Can create roles.',
  ),
  PermissionDefinition(
    key: 'settings.roles.edit',
    module: 'settings',
    resource: 'roles',
    action: PermissionActions.edit,
    label: 'Edit Roles',
    description: 'Can edit roles.',
  ),
  PermissionDefinition(
    key: 'settings.roles.delete',
    module: 'settings',
    resource: 'roles',
    action: PermissionActions.delete,
    label: 'Delete Roles',
    description: 'Can delete roles.',
  ),
  PermissionDefinition(
    key: 'settings.transaction_series.view',
    module: 'settings',
    resource: 'transaction_series',
    action: PermissionActions.view,
    label: 'View Transaction Series',
    description: 'Can view transaction series.',
  ),
  PermissionDefinition(
    key: 'settings.transaction_series.create',
    module: 'settings',
    resource: 'transaction_series',
    action: PermissionActions.create,
    label: 'Create Transaction Series',
    description: 'Can create transaction series.',
  ),
  PermissionDefinition(
    key: 'settings.transaction_series.edit',
    module: 'settings',
    resource: 'transaction_series',
    action: PermissionActions.edit,
    label: 'Edit Transaction Series',
    description: 'Can edit transaction series.',
  ),
  PermissionDefinition(
    key: 'settings.transaction_series.delete',
    module: 'settings',
    resource: 'transaction_series',
    action: PermissionActions.delete,
    label: 'Delete Transaction Series',
    description: 'Can delete transaction series.',
  ),
  PermissionDefinition(
    key: 'reports.dashboard.view',
    module: 'reports',
    resource: 'dashboard',
    action: PermissionActions.view,
    label: 'View Dashboard',
    description: 'Can view dashboard cards and charts.',
  ),
  PermissionDefinition(
    key: 'reports.center.view',
    module: 'reports',
    resource: 'center',
    action: PermissionActions.view,
    label: 'View Report Center',
    description: 'Can view report center.',
  ),
  PermissionDefinition(
    key: 'reports.center.export',
    module: 'reports',
    resource: 'center',
    action: PermissionActions.export,
    label: 'Export Reports',
    description: 'Can export reports.',
  ),
  PermissionDefinition(
    key: 'reports.audit_log.view',
    module: 'reports',
    resource: 'audit_log',
    action: PermissionActions.view,
    label: 'View Audit Logs',
    description: 'Can view audit logs.',
  ),
  PermissionDefinition(
    key: 'reports.document.view',
    module: 'reports',
    resource: 'document',
    action: PermissionActions.view,
    label: 'View Documents',
    description: 'Can view documents.',
  ),
];

final Map<String, PermissionDefinition> permissionRegistryByKey = {
  for (final permission in permissionsRegistry) permission.key: permission,
};
