const List<String> reportNavigationCategories = [
  'Business Overview',
  'Sales',
  'Inventory',
  'Advanced Inventory',
  'Inventory Valuation',
  'Receivables',
  'Payments Received',
  'Recurring Invoices',
  'Payables',
  'Purchases and Expenses',
  'Taxes',
  'Banking',
  'Accountant',
  'Currency',
  'Activity',
  'Automation',
];

const Map<String, List<String>> reportNavigationReportsByCategory = {
  'Business Overview': [
    'Profit and Loss',
    'Profit and Loss (Schedule III)',
    'Horizontal Profit and Loss',
    'Cash Flow Statement',
    'Balance Sheet',
    'Horizontal Balance Sheet',
    'Balance Sheet (Schedule III)',
    'Business Performance Ratios',
    'Movement of Equity',
  ],
  'Sales': [
    'Sales by Customer',
    'Sales by Item',
    'Sales by Sales Person',
    'Sales Summary',
    'Profit By Item',
    'Sales Channel Integrations Sync Summary',
  ],
  'Inventory': [
    'Inventory Summary',
    'Committed Stock Details',
    'Inventory Aging Summary',
    'Stock Summary',
    'Assembly Details',
    'Stock Movement',
    'Inventory Adjustment Summary',
    'Inventory Adjustment Details',
    'Inventory Turnover By Quantity',
  ],
  'Advanced Inventory': [
    'Batch Details',
    'Serial Number Details',
  ],
  'Inventory Valuation': [
    'Inventory Valuation Summary',
    'FIFO Cost Lot Tracking',
    'ABC classification',
    'Landed Cost Summary',
    'Inventory Turnover By Amount',
    'Weighted Average Costing Summary',
  ],
  'Receivables': [
    'AR Aging Summary',
    'AR Aging Details',
    'Invoice Details',
    'Retainer Invoice Details',
    'Sales Order Details',
    'Delivery Challan Details',
    'Quote Details',
    'Customer Balance Summary',
    'Receivable Summary',
    'Receivable Details',
  ],
  'Payments Received': [
    'Payments Received',
    'Time to Get Paid',
    'Credit Note Details',
    'Refund History',
  ],
  'Recurring Invoices': ['Recurring Invoice Details'],
  'Payables': [
    'Vendor Balance Summary',
    'AP Aging Summary',
    'AP Aging Details',
    'Bill Details',
    'Vendor Credit Details',
    'Payments Made',
    'Refund History',
    'Purchase Order Details',
    'Purchase Orders by Vendor',
    'Purchase Order by Item',
    'Payable Summary',
    'Payable Details',
  ],
  'Purchases and Expenses': [
    'Purchases by Vendor',
    'Purchases by Item',
    'Expense Details',
    'Expenses by Category',
    'Expenses by Customer',
    'Expenses by Employee',
    'Billable Expense Details',
  ],
  'Taxes': [
    'Tax Summary',
    'Annual Summary (GSTR-9)',
    'TDS Summary',
    'TDS Receivable Summary',
    'GSTR-7 (Return for Tax Deducted at Source)',
    'TCS Payable Summary (Form No. 27EQ)',
    'Invoice Furnishing Facility (IFF)',
    'PMT-06 (Self Assessment Basis)',
    'GSTR-3B Summary',
    'Summary of Outward Supplies',
    'Summary of Inward Supplies',
    'Self-invoice Summary',
    'KFC-A Summary',
  ],
  'Banking': ['Reconciliation Status'],
  'Accountant': [
    'Account Transactions',
    'Account Type Summary',
    'Account Type Transactions',
    'Day Book',
    'General Ledger',
    'Detailed General Ledger',
    'Journal Report',
    'Trial Balance',
  ],
  'Currency': ['Realized Gain or Loss', 'Unrealized Gain or Loss'],
  'Activity': [
    'System Mails',
    'Activity Logs & Audit Trail',
    'Exception Report',
    'Portal Activities',
    'Customer Reviews',
    'API Usage',
    'Pending Inventory Valuations',
  ],
  'Automation': [
    'Scheduled Date Based Workflow Rules',
    'Scheduled Time Based Workflow Actions',
    'Workflow Execution Logs',
  ],
};
