BEGIN;

ALTER TABLE public.schedules
ADD COLUMN IF NOT EXISTS schedule_code character varying(30),
ADD COLUMN IF NOT EXISTS reference_description text,
ADD COLUMN IF NOT EXISTS requires_prescription boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS requires_h1_register boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS is_narcotic boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS requires_batch_tracking boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_common boolean NOT NULL DEFAULT false;

ALTER TABLE public.buying_rules
ADD COLUMN IF NOT EXISTS rule_description text,
ADD COLUMN IF NOT EXISTS system_behavior text,
ADD COLUMN IF NOT EXISTS associated_schedule_codes text[] NOT NULL DEFAULT ARRAY[]::text[],
ADD COLUMN IF NOT EXISTS requires_rx boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS requires_patient_info boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS is_saleable boolean NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS log_to_special_register boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS requires_doctor_name boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS requires_prescription_date boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS requires_age_check boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS institutional_only boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS blocks_retail_sale boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS quantity_limit integer,
ADD COLUMN IF NOT EXISTS allows_refill boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;

ALTER TABLE public.storage_locations
ADD COLUMN IF NOT EXISTS storage_type character varying(255),
ADD COLUMN IF NOT EXISTS display_text character varying(255),
ADD COLUMN IF NOT EXISTS common_examples text,
ADD COLUMN IF NOT EXISTS min_temp_c numeric(5,2),
ADD COLUMN IF NOT EXISTS max_temp_c numeric(5,2),
ADD COLUMN IF NOT EXISTS is_cold_chain boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS requires_fridge boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;

INSERT INTO public.schedules (
  shedule_name,
  schedule_code,
  reference_description,
  requires_prescription,
  requires_h1_register,
  is_narcotic,
  requires_batch_tracking,
  sort_order,
  is_common,
  is_active
)
VALUES
  (
    'NONE / GENERAL',
    'OTC',
    'Over-the-counter drugs; no prescription required.',
    false,
    false,
    false,
    false,
    10,
    true,
    true
  ),
  (
    'SCHEDULE G',
    'SCH-G',
    'Drugs requiring medical supervision (Caution label).',
    true,
    false,
    false,
    true,
    20,
    true,
    true
  ),
  (
    'SCHEDULE H',
    'SCH-H',
    'Prescription-only drugs (Standard Rx).',
    true,
    false,
    false,
    true,
    30,
    true,
    true
  ),
  (
    'SCHEDULE H1',
    'SCH-H1',
    'Restricted antibiotics and habit-forming drugs. Requires separate register.',
    true,
    true,
    false,
    true,
    40,
    true,
    true
  ),
  (
    'SCHEDULE X',
    'SCH-X',
    'Highly regulated narcotics and psychotropics. Requires NRx label and lock/key.',
    true,
    false,
    true,
    true,
    50,
    false,
    true
  ),
  (
    'SCHEDULE C',
    'SCH-C',
    'Biological and injectable products.',
    false,
    false,
    false,
    true,
    60,
    false,
    true
  ),
  (
    'SCHEDULE C1',
    'SCH-C1',
    'Non-parenteral biological products such as oral hormones and vitamins.',
    false,
    false,
    false,
    true,
    70,
    false,
    true
  ),
  (
    'SCHEDULE E1',
    'SCH-E1',
    'Poisonous substances under Ayurvedic, Siddha, and Unani systems.',
    false,
    false,
    false,
    true,
    80,
    false,
    true
  ),
  (
    'SCHEDULE K',
    'SCH-K',
    'Drugs exempted from certain sale regulations such as household remedies.',
    false,
    false,
    false,
    true,
    90,
    false,
    true
  )
ON CONFLICT (shedule_name) DO UPDATE
SET
  schedule_code = EXCLUDED.schedule_code,
  reference_description = EXCLUDED.reference_description,
  requires_prescription = EXCLUDED.requires_prescription,
  requires_h1_register = EXCLUDED.requires_h1_register,
  is_narcotic = EXCLUDED.is_narcotic,
  requires_batch_tracking = EXCLUDED.requires_batch_tracking,
  sort_order = EXCLUDED.sort_order,
  is_common = EXCLUDED.is_common,
  is_active = EXCLUDED.is_active;

INSERT INTO public.buying_rules (
  buying_rule,
  rule_description,
  system_behavior,
  associated_schedule_codes,
  requires_rx,
  requires_patient_info,
  is_saleable,
  log_to_special_register,
  requires_doctor_name,
  requires_prescription_date,
  requires_age_check,
  institutional_only,
  blocks_retail_sale,
  quantity_limit,
  allows_refill,
  sort_order,
  is_active
)
VALUES
  (
    'No Restriction (OTC)',
    'Direct sale allowed; no prompts.',
    'Direct sale allowed with no prescription prompts. Recommended default for OTC and general items.',
    ARRAY['OTC'],
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    NULL,
    false,
    10,
    true
  ),
  (
    'Prescription Required',
    'System prompts for Doctor''s Name and Prescription Date.',
    'Requires the cashier to capture doctor name and prescription date before billing.',
    ARRAY['SCH-G', 'SCH-H'],
    true,
    false,
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    NULL,
    false,
    20,
    true
  ),
  (
    'Mandatory H1 Register',
    'Prompts for patient name, address, and phone number and logs the sale in the H1 register.',
    'Requires prescription details plus patient information and H1 register logging.',
    ARRAY['SCH-H1'],
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    NULL,
    false,
    30,
    true
  ),
  (
    'Narcotic Control (Strict)',
    'Requires special license verification and duplicate prescription entry.',
    'Strict narcotic workflow with patient verification and special register logging.',
    ARRAY['SCH-X'],
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    NULL,
    false,
    40,
    true
  ),
  (
    'Age Restricted',
    'System prompts to verify the buyer is 18+ years old.',
    'Prompts the operator to verify age before sale completion.',
    ARRAY[]::text[],
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    false,
    false,
    NULL,
    false,
    50,
    true
  ),
  (
    'Institutional Sale Only',
    'Blocks sale to individual retail customers; allowed only for hospitals.',
    'Restricts sale to institutional customers such as hospitals or clinics.',
    ARRAY[]::text[],
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    true,
    NULL,
    false,
    60,
    true
  ),
  (
    'Physician Sample (Not for Sale)',
    'Blocks sale entirely and prevents billing of samples provided by medical representatives.',
    'Non-saleable item classification for physician samples.',
    ARRAY[]::text[],
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    NULL,
    false,
    70,
    true
  ),
  (
    'Quantity Restricted',
    'Limits the number of units per invoice.',
    'Enforces quantity restrictions for scarce or habit-forming products.',
    ARRAY[]::text[],
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    2,
    false,
    80,
    true
  ),
  (
    'Chronic Care (Refillable)',
    'Allows sale based on a standing prescription for long-term use.',
    'Supports repeat dispensing for chronic-care medicines such as BP, diabetes, or thyroid drugs.',
    ARRAY[]::text[],
    true,
    false,
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    NULL,
    true,
    90,
    true
  )
ON CONFLICT (buying_rule) DO UPDATE
SET
  rule_description = EXCLUDED.rule_description,
  system_behavior = EXCLUDED.system_behavior,
  associated_schedule_codes = EXCLUDED.associated_schedule_codes,
  requires_rx = EXCLUDED.requires_rx,
  requires_patient_info = EXCLUDED.requires_patient_info,
  is_saleable = EXCLUDED.is_saleable,
  log_to_special_register = EXCLUDED.log_to_special_register,
  requires_doctor_name = EXCLUDED.requires_doctor_name,
  requires_prescription_date = EXCLUDED.requires_prescription_date,
  requires_age_check = EXCLUDED.requires_age_check,
  institutional_only = EXCLUDED.institutional_only,
  blocks_retail_sale = EXCLUDED.blocks_retail_sale,
  quantity_limit = EXCLUDED.quantity_limit,
  allows_refill = EXCLUDED.allows_refill,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active;

INSERT INTO public.storage_locations (
  location_name,
  storage_type,
  temperature_range,
  display_text,
  description,
  common_examples,
  min_temp_c,
  max_temp_c,
  is_cold_chain,
  requires_fridge,
  sort_order,
  is_active
)
VALUES
  (
    'Freezer',
    'Freezer',
    '-20°C to -10°C',
    'Store in a Freezer (-20°C to -10°C)',
    'Recommended for products that require freezer storage.',
    'Polio Vaccine (OPV), specialized injections',
    -20.00,
    -10.00,
    true,
    true,
    10,
    true
  ),
  (
    'Cold / Fridge',
    'Cold / Fridge',
    '2°C to 8°C',
    'Store in a Refrigerator (2°C to 8°C)',
    'Use for cold-chain medicines that must be moved to refrigeration immediately.',
    'Insulin, Vaccines, Sera, certain Eye Drops',
    2.00,
    8.00,
    true,
    true,
    20,
    true
  ),
  (
    'Cool',
    'Cool',
    '8°C to 25°C',
    'Store in a Cool Place (8°C to 25°C)',
    'Suitable for products requiring a cool environment after preparation or reconstitution.',
    'Antibiotic syrups after reconstitution, some ointments',
    8.00,
    25.00,
    false,
    false,
    30,
    true
  ),
  (
    'Room Temp',
    'Room Temp',
    'Up to 25°C',
    'Store below 25°C',
    'Use for products that should remain under standard room-temperature control.',
    'Most tablets, capsules, and general medicines',
    NULL,
    25.00,
    false,
    false,
    40,
    true
  ),
  (
    'Normal Temp',
    'Normal Temp',
    'Up to 30°C',
    'Store below 30°C',
    'Default storage for stable medicines and general inventory with no special handling.',
    'Bandages, surgical items, stable powders',
    NULL,
    30.00,
    false,
    false,
    50,
    true
  ),
  (
    'Dry Place',
    'Dry Place',
    'Low Humidity',
    'Store in a Dry Place',
    'Use for moisture-sensitive products.',
    'Effervescent tablets, moisture-sensitive strips',
    NULL,
    NULL,
    false,
    false,
    60,
    true
  ),
  (
    'Dark Place',
    'Dark Place',
    'Protect from Light',
    'Protect from Light',
    'Use for light-sensitive medicines and products.',
    'Multivitamins, Nitroglycerin injections, dark glass bottles',
    NULL,
    NULL,
    false,
    false,
    70,
    true
  )
ON CONFLICT (location_name) DO UPDATE
SET
  storage_type = EXCLUDED.storage_type,
  temperature_range = EXCLUDED.temperature_range,
  display_text = EXCLUDED.display_text,
  description = EXCLUDED.description,
  common_examples = EXCLUDED.common_examples,
  min_temp_c = EXCLUDED.min_temp_c,
  max_temp_c = EXCLUDED.max_temp_c,
  is_cold_chain = EXCLUDED.is_cold_chain,
  requires_fridge = EXCLUDED.requires_fridge,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active;

COMMIT;
